/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{572:function(xa,ta,n){n.r(ta);var qa=n(0),na=n(594),oa=n(595),ha;(function(la){la[la.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";la[la.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";la[la.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ha||(ha={}));xa=function(){function la(ia){this.aa=ia;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED}la.prototype.Gta=function(){var ia=this;return function(z,
aa,r){return Object(qa.b)(ia,void 0,void 0,function(){var h,f,a,b,e,w,ea,y=this,ba;return Object(qa.d)(this,function(x){switch(x.label){case 0:if(this.state!==ha.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];h=this.aa.getDocument().qw();return[4,this.Bra(h)];case 1:f=x.ba(),a=this.xla(f),this.XP=null!==(ba=null===a||void 0===a?void 0:a.parse())&&void 0!==ba?ba:null,this.state=null===this.XP?ha.EXTERNAL_XFDF_NOT_AVAILABLE:ha.EXTERNAL_XFDF_AVAILABLE,x.label=2;case 2:if(this.state===ha.EXTERNAL_XFDF_NOT_AVAILABLE)return r(z),
[2];b=new DOMParser;e=b.parseFromString(z,"text/xml");aa.forEach(function(fa){y.merge(e,y.XP,fa-1)});w=new XMLSerializer;ea=w.serializeToString(e);r(ea);return[2]}})})}};la.prototype.dV=function(ia){this.Bra=ia};la.prototype.Af=function(){this.XP=void 0;this.state=ha.EXTERNAL_XFDF_NOT_REQUESTED};la.prototype.xla=function(ia){return ia?Array.isArray(ia)?new na.a(ia):"string"!==typeof ia?null:(new DOMParser).parseFromString(ia,"text/xml").querySelector("xfdf > add")?new na.a(ia):new oa.a(ia):null};
la.prototype.merge=function(ia,z,aa){var r=this;0===aa&&(this.Vwa(ia,z.Fs),this.Xwa(ia,z.CP));var h=z.ea[aa];h&&(this.Ywa(ia,h.nq),this.$wa(ia,h.Pba,z.LA),this.Zwa(ia,h.page,aa),this.Wwa(ia,h.w1));h=this.aa.Fb();if(aa===h-1){var f=z.LA;Object.keys(f).forEach(function(a){f[a].CR||r.C6(ia,a,f[a])})}};la.prototype.Vwa=function(ia,z){null!==z&&(ia=this.Oz(ia),this.lu(ia,"calculation-order",z))};la.prototype.Xwa=function(ia,z){null!==z&&(ia=this.Oz(ia),this.lu(ia,"document-actions",z))};la.prototype.Ywa=
function(ia,z){var aa=this,r=this.Nz(ia.querySelector("xfdf"),"annots");Object.keys(z).forEach(function(h){aa.lu(r,'[name="'+h+'"]',z[h])})};la.prototype.$wa=function(ia,z,aa){var r=this;if(0!==z.length){var h=this.Oz(ia);z.forEach(function(f){var a=f.getAttribute("field"),b=aa[a];b&&(r.C6(ia,a,b),r.lu(h,"null",f))})}};la.prototype.C6=function(ia,z,aa){var r=this.Oz(ia),h=r.querySelector('ffield[name="'+z+'"]');null!==aa.QH&&null===h&&this.lu(r,'ffield[name="'+z+'"]',aa.QH);ia=this.Nz(ia.querySelector("xfdf"),
"xfdf > fields","fields");z=z.split(".");this.YT(ia,z,0,aa.value);aa.CR=!0};la.prototype.Zwa=function(ia,z,aa){null!==z&&(ia=this.Oz(ia),ia=this.Nz(ia,"pages"),this.lu(ia,'[number="'+(aa+1)+'"]',z))};la.prototype.Wwa=function(ia,z){Object.keys(z).forEach(function(aa){(aa=ia.querySelector('annots [name="'+aa+'"]'))&&aa.parentElement.removeChild(aa)})};la.prototype.YT=function(ia,z,aa,r){if(aa===z.length)z=document.createElementNS("","value"),z.textContent=r,this.lu(ia,"value",z);else{var h=z[aa];this.Nz(ia,
'[name="'+h+'"]',"field").setAttribute("name",h);ia=ia.querySelectorAll('[name="'+h+'"]');1===ia.length?this.YT(ia[0],z,aa+1,r):(h=this.Rpa(ia),this.YT(aa===z.length-1?h:this.GFa(ia,h),z,aa+1,r))}};la.prototype.Rpa=function(ia){for(var z=null,aa=0;aa<ia.length;aa++){var r=ia[aa];if(0===r.childElementCount||1===r.childElementCount&&"value"===r.children[0].tagName){z=r;break}}return z};la.prototype.GFa=function(ia,z){for(var aa=0;aa<ia.length;aa++)if(ia[aa]!==z)return ia[aa];return null};la.prototype.lu=
function(ia,z,aa){z=ia.querySelector(z);null!==z&&ia.removeChild(z);ia.appendChild(aa)};la.prototype.Oz=function(ia){var z=ia.querySelector("pdf-info");if(null!==z)return z;z=this.Nz(ia.querySelector("xfdf"),"pdf-info");z.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");z.setAttribute("version","2");z.setAttribute("import-version","4");return z};la.prototype.Nz=function(ia,z,aa){var r=ia.querySelector(z);if(null!==r)return r;r=document.createElementNS("",aa||z);ia.appendChild(r);return r};return la}();
ta["default"]=xa},583:function(xa,ta){xa=function(){function n(){}n.prototype.eG=function(qa){var na={Fs:null,CP:null,LA:{},ea:{}};qa=(new DOMParser).parseFromString(qa,"text/xml");na.Fs=qa.querySelector("pdf-info calculation-order");na.CP=qa.querySelector("pdf-info document-actions");na.LA=this.nya(qa);na.ea=this.Bya(qa);return na};n.prototype.nya=function(qa){var na=qa.querySelector("fields");qa=qa.querySelectorAll("pdf-info > ffield");if(null===na&&null===qa)return{};var oa={};this.Vha(oa,na);
this.Tha(oa,qa);return oa};n.prototype.Vha=function(qa,na){if(null!==na&&na.children){for(var oa=[],ha=0;ha<na.children.length;ha++){var la=na.children[ha];oa.push({name:la.getAttribute("name"),element:la})}for(;0!==oa.length;)for(na=oa.shift(),ha=0;ha<na.element.children.length;ha++)la=na.element.children[ha],"value"===la.tagName?qa[na.name]={value:la.textContent,QH:null,CR:!1}:la.children&&oa.push({name:na.name+"."+la.getAttribute("name"),element:la})}};n.prototype.Tha=function(qa,na){na.forEach(function(oa){var ha=
oa.getAttribute("name");qa[ha]?qa[ha].QH=oa:qa[ha]={value:null,QH:oa,CR:!1}})};n.prototype.Bya=function(qa){var na=this,oa={};qa.querySelectorAll("pdf-info widget").forEach(function(ha){var la=parseInt(ha.getAttribute("page"),10)-1;na.fJ(oa,la);oa[la].Pba.push(ha)});qa.querySelectorAll("pdf-info page").forEach(function(ha){var la=parseInt(ha.getAttribute("number"),10)-1;na.fJ(oa,la);oa[la].page=ha});this.A3(qa).forEach(function(ha){var la=parseInt(ha.getAttribute("page"),10),ia=ha.getAttribute("name");
na.fJ(oa,la);oa[la].nq[ia]=ha});this.h3(qa).forEach(function(ha){var la=parseInt(ha.getAttribute("page"),10);ha=ha.textContent;na.fJ(oa,la);oa[la].w1[ha]=!0});return oa};n.prototype.fJ=function(qa,na){qa[na]||(qa[na]={nq:{},w1:{},Pba:[],page:null})};return n}();ta.a=xa},594:function(xa,ta,n){var qa=n(0),na=n(1);n.n(na);xa=function(oa){function ha(la){var ia=oa.call(this)||this;ia.zpa=Array.isArray(la)?la:[la];return ia}Object(qa.c)(ha,oa);ha.prototype.parse=function(){var la=this,ia={Fs:null,CP:null,
LA:{},ea:{}};this.zpa.forEach(function(z){ia=Object(na.merge)(ia,la.eG(z))});return ia};ha.prototype.A3=function(la){var ia=[];la.querySelectorAll("add > *").forEach(function(z){ia.push(z)});la.querySelectorAll("modify > *").forEach(function(z){ia.push(z)});return ia};ha.prototype.h3=function(la){return la.querySelectorAll("delete > *")};return ha}(n(583).a);ta.a=xa},595:function(xa,ta,n){var qa=n(0);xa=function(na){function oa(ha){var la=na.call(this)||this;la.Apa=ha;return la}Object(qa.c)(oa,na);
oa.prototype.parse=function(){return this.eG(this.Apa)};oa.prototype.A3=function(ha){return ha.querySelectorAll("annots > *")};oa.prototype.h3=function(){return[]};return oa}(n(583).a);ta.a=xa}}]);}).call(this || window)
