/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{556:function(xa,ta,n){n.r(ta);n.d(ta,"ByteRangeRequest",function(){return w});var qa=n(0),na=n(1);n.n(na);var oa=n(3),ha=n(187);xa=n(116);var la=n(311),ia=n(86),z=n(91),aa=n(310),r=n(205);n=n(477);var h=[],f=[],a=window,b=function(){return function(){this.np=1}}(),e;(function(y){y[y.UNSENT=0]="UNSENT";y[y.DONE=4]="DONE"})(e||(e={}));var w=function(){function y(ba,x,fa,ca){var ma=this;this.url=ba;this.range=x;this.Ag=fa;this.withCredentials=
ca;this.tfa=e;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);a.Uint8Array&&(this.request.responseType="arraybuffer");ca&&(this.request.withCredentials=ca);ea.DISABLE_RANGE_HEADER||(Object(na.isUndefined)(x.stop)?this.request.setRequestHeader("Range","bytes="+x.start):this.request.setRequestHeader("Range",["bytes=",x.start,"-",x.stop-1].join("")));fa&&Object.keys(fa).forEach(function(ka){ma.request.setRequestHeader(ka,fa[ka])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):
this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=aa.a.NOT_STARTED}y.prototype.start=function(ba){var x=this,fa=this.request;fa.onreadystatechange=function(){if(x.aborted)return x.status=aa.a.ABORTED,ba({code:aa.a.ABORTED});if(this.readyState===x.tfa.DONE){x.AI();var ca=0===window.document.URL.indexOf("file:///");200===fa.status||206===fa.status||ca&&0===fa.status?(ca=a.T3(this),x.TV(ca,ba)):(x.status=aa.a.ERROR,ba({code:x.status,status:x.status}))}};this.request.send(null);
this.status=aa.a.STARTED};y.prototype.TV=function(ba,x){this.status=aa.a.SUCCESS;if(x)return x(!1,ba)};y.prototype.abort=function(){this.AI();this.aborted=!0;this.request.abort()};y.prototype.AI=function(){var ba=Object(r.c)(this.url,this.range,f);-1!==ba&&f.splice(ba,1);if(0<h.length){ba=h.shift();var x=new y(ba.url,ba.range,this.Ag,this.withCredentials);ba.request=x;f.push(ba);x.start(Object(r.d)(ba))}};y.prototype.extend=function(ba){var x=Object.assign({},this,ba.prototype);x.constructor=ba;return x};
return y}(),ea=function(y){function ba(x,fa,ca,ma,ka){ca=y.call(this,x,ca,ma)||this;ca.ml={};ca.IG=fa;ca.url=x;ca.DISABLE_RANGE_HEADER=!1;ca.dD=w;ca.jX=3;ca.Ag=ka||{};return ca}Object(qa.c)(ba,y);ba.prototype.oA=function(x,fa,ca){var ma=-1===x.indexOf("?")?"?":"&";switch(ca){case !1:case z.a.NEVER_CACHE:x=x+ma+"_="+Object(na.uniqueId)();break;case !0:case z.a.CACHE:x=x+ma+"_="+fa.start+","+(Object(na.isUndefined)(fa.stop)?"":fa.stop)}return x};ba.prototype.c1=function(x,fa,ca,ma){void 0===ca&&(ca=
{});return new this.dD(x,fa,ca,ma)};ba.prototype.opa=function(x,fa,ca,ma,ka){for(var ja=0;ja<h.length;ja++)if(Object(na.isEqual)(h[ja].range,fa)&&Object(na.isEqual)(h[ja].url,x))return h[ja].ui.push(ma),h[ja].RJ++,null;for(ja=0;ja<f.length;ja++)if(Object(na.isEqual)(f[ja].range,fa)&&Object(na.isEqual)(f[ja].url,x))return f[ja].ui.push(ma),f[ja].RJ++,null;ca={url:x,range:fa,IG:ca,ui:[ma],RJ:1};if(0===h.length&&f.length<this.jX)return f.push(ca),ca.request=this.c1(x,fa,ka,this.withCredentials),ca;h.push(ca);
return null};ba.prototype.mr=function(x,fa,ca){var ma=this.oA(x,fa,this.IG);(x=this.opa(ma,fa,this.IG,ca,this.Ag))&&x.request.start(Object(r.d)(x));return function(){var ka=Object(r.c)(ma,fa,f);if(-1!==ka){var ja=--f[ka].RJ;0===ja&&f[ka].request&&f[ka].request.abort()}else ka=Object(r.c)(ma,fa,h),-1!==ka&&(ja=--h[ka].RJ,0===ja&&h.splice(ka,1))}};ba.prototype.m3=function(){return{start:-ha.a}};ba.prototype.Pta=function(){var x=-(ha.a+ha.e);return{start:x-ha.d,end:x}};ba.prototype.ix=function(x){var fa=
this;this.QG=!0;var ca=ha.a;this.mr(this.url,this.m3(),function(ma,ka,ja){function ra(){var pa=fa.Ce.i3();fa.mr(fa.url,pa,function(sa,ua){if(sa)return Object(oa.j)("Error loading central directory: "+sa),x(sa);ua=Object(ia.a)(ua);if(ua.length!==pa.stop-pa.start)return x("Invalid XOD file: Zip central directory data is wrong size! Should be "+(pa.stop-pa.start)+" but is "+ua.length);fa.Ce.G8(ua);fa.KO=!0;fa.QG=!1;return x(!1)})}if(ma)return Object(oa.j)("Error loading end header: "+ma),x(ma,ka,ja);
ka=Object(ia.a)(ka);if(ka.length!==ca)return x("Invalid XOD file: Zip end header data is wrong size!");try{fa.Ce=new la.a(ka)}catch(pa){return x(pa)}fa.Ce.fwa?fa.mr(fa.url,fa.Pta(),function(pa,sa){if(pa)return Object(oa.j)("Error loading zip64 header: "+pa),x(pa);sa=Object(ia.a)(sa);fa.Ce.Gwa(sa);ra()}):ra()})};ba.prototype.N3=function(x){x(Object.keys(this.Ce.Kq))};ba.prototype.aU=function(x,fa){var ca=this;if(this.Ce.P0(x)){var ma=this.Ce.eB(x);if(ma in this.ml){var ka=this.Si[x];ka.Nv=this.ml[ma];
ka.Nv.np++;ka.cancel=ka.Nv.cancel}else{var ja=this.Ce.Ira(x),ra=this.mr(this.url,ja,function(sa,ua){sa?(Object(oa.j)('Error loading part "'+x+'": '+sa),ca.mr(ca.url,ja,function(wa,Fa){if(wa)return fa(wa,x);ca.K8(Fa,ja,ma,x,fa)})):ca.K8(ua,ja,ma,x,fa)}),pa=this.Si[x];pa&&(pa.Eaa=!0,pa.cancel=function(){pa.Nv.np--;0===pa.Nv.np&&(ra(),delete ca.ml[ma])},this.ml[ma]=new b(ma),pa.Nv=this.ml[ma],pa.Nv.cancel=pa.cancel)}}else delete this.Si[x],fa(Error('File not found: "'+x+'"'),x)};ba.prototype.K8=function(x,
fa,ca,ma,ka){if(x.length!==fa.stop-fa.start)ka(Error("Part data is wrong size!"),ma);else{do{if(!this.ml[ca])return;ma=this.ml[ca].np;for(var ja=fa.mu.length,ra=0;ra<ja;++ra){var pa=fa.mu[ra];ka(!1,pa.ju,x["string"===typeof x?"substring":"subarray"](pa.start,pa.stop),this.Ce.k5(pa.ju));pa.ju in this.Si&&delete this.Si[pa.ju]}}while(ma!==this.ml[ca].np);delete this.ml[ca]}};ba.DISABLE_RANGE_HEADER=!1;ba.jX=3;return ba}(xa.a);(function(y){function ba(x,fa,ca){var ma=y.call(this)||this,ka;for(ka in x)ma[ka]=
x[ka];ma.VKa=x;ma.startOffset=fa;ma.endOffset=ca;ma.c1=function(ja,ra,pa,sa){Object(na.isUndefined)(ra.stop)?(ra.start+=ma.endOffset,ra.stop=ma.endOffset):(ra.start+=ma.startOffset,ra.stop+=ma.startOffset);ja=ma.oA(ma.url,ra,ma.IG);return new x.dD(ja,ra,pa,sa)};return ma}Object(qa.c)(ba,y);return ba})(ea);Object(n.a)(ea);Object(n.b)(ea);ta["default"]=ea}}]);}).call(this || window)
