/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{565:function(xa,ta,n){n.r(ta);var qa=n(0),na=n(1);n.n(na);var oa=n(3),ha=n(187);xa=n(54);var la=n(116),ia=n(311),z=n(91),aa=n(310);n=n(477);var r=window,h=function(){function b(e,w,ea){var y=-1===e.indexOf("?")?"?":"&";switch(w){case z.a.NEVER_CACHE:this.url=e+y+"_="+Object(na.uniqueId)();break;default:this.url=e}this.Ag=ea;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=aa.a.NOT_STARTED}b.prototype.start=function(e,w){var ea=this,y=this,ba=this.request,x;y.hC=0;e&&Object.keys(e).forEach(function(fa){ea.request.setRequestHeader(fa,e[fa])});w&&(this.request.withCredentials=w);this.vK=setInterval(function(){var fa=0===window.document.URL.indexOf("file:///");fa=200===ba.status||
fa&&0===ba.status;if(ba.readyState!==aa.b.DONE||fa){try{ba.responseText}catch(ca){return}y.hC<ba.responseText.length&&(x=y.Cza())&&y.trigger(b.Events.DATA,[x]);0===ba.readyState&&(clearInterval(y.vK),y.trigger(b.Events.DONE))}else clearInterval(y.vK),y.trigger(b.Events.DONE,["Error received return status "+ba.status])},1E3);this.request.send(null);this.status=aa.a.STARTED};b.prototype.Cza=function(){var e=this.request,w=e.responseText;if(0!==w.length)if(this.hC===w.length)clearInterval(this.vK),this.trigger(b.Events.DONE);
else return w=Math.min(this.hC+3E6,w.length),e=r.T3(e,this.hC,!0,w),this.hC=w,e};b.prototype.abort=function(){clearInterval(this.vK);var e=this;this.request.onreadystatechange=function(){Object(oa.j)("StreamingRequest aborted");e.status=aa.a.ABORTED;return e.trigger(b.Events.ABORTED)};this.request.abort()};b.prototype.finish=function(){var e=this;this.request.onreadystatechange=function(){e.status=aa.a.SUCCESS;return e.trigger(b.Events.DONE)};this.request.abort()};b.Events={DONE:"done",DATA:"data",
ABORTED:"aborted"};return b}();Object(xa.a)(h);var f;(function(b){b[b.LOCAL_HEADER=0]="LOCAL_HEADER";b[b.FILE=1]="FILE";b[b.CENTRAL_DIR=2]="CENTRAL_DIR"})(f||(f={}));var a=function(b){function e(){var w=b.call(this)||this;w.buffer="";w.state=f.LOCAL_HEADER;w.LV=4;w.Yo=null;w.ox=ha.c;w.Kq={};return w}Object(qa.c)(e,b);e.prototype.uza=function(w){var ea;for(w=this.buffer+w;w.length>=this.ox;)switch(this.state){case f.LOCAL_HEADER:this.Yo=ea=this.Gza(w.slice(0,this.ox));if(ea.by!==ha.g)throw Error("Wrong signature in local header: "+
ea.by);w=w.slice(this.ox);this.state=f.FILE;this.ox=ea.zO+ea.bu+ea.JA+this.LV;this.trigger(e.Events.HEADER,[ea]);break;case f.FILE:this.Yo.name=w.slice(0,this.Yo.bu);this.Kq[this.Yo.name]=this.Yo;ea=this.ox-this.LV;var y=w.slice(this.Yo.bu+this.Yo.JA,ea);this.trigger(e.Events.FILE,[this.Yo.name,y,this.Yo.SO]);w=w.slice(ea);if(w.slice(0,this.LV)===ha.h)this.state=f.LOCAL_HEADER,this.ox=ha.c;else return this.state=f.CENTRAL_DIR,!0}this.buffer=w;return!1};e.Events={HEADER:"header",FILE:"file"};return e}(ia.a);
Object(xa.a)(a);xa=function(b){function e(w,ea,y,ba,x){y=b.call(this,w,y,ba)||this;y.url=w;y.stream=new h(w,ea);y.Ce=new a;y.n8=window.createPromiseCapability();y.Q8={};y.Ag=x;return y}Object(qa.c)(e,b);e.prototype.mD=function(w){var ea=this;this.request([this.Cl,this.xn,this.Al]);this.stream.addEventListener(h.Events.DATA,function(y){try{if(ea.Ce.uza(y))return ea.stream.finish()}catch(ba){throw ea.stream.abort(),ea.kt(ba),w(ba),ba;}});this.stream.addEventListener(h.Events.DONE,function(y){ea.Tya=
!0;ea.n8.resolve();y&&(ea.kt(y),w(y))});this.Ce.addEventListener(a.Events.HEADER,Object(na.bind)(this.P8,this));this.Ce.addEventListener(a.Events.FILE,Object(na.bind)(this.Xza,this));return this.stream.start(this.Ag,this.withCredentials)};e.prototype.N3=function(w){var ea=this;this.n8.promise.then(function(){w(Object.keys(ea.Ce.Kq))})};e.prototype.zr=function(){return!0};e.prototype.request=function(w){var ea=this;this.Tya&&w.forEach(function(y){ea.Q8[y]||ea.WFa(y)})};e.prototype.P8=function(){};
e.prototype.abort=function(){this.stream&&this.stream.abort()};e.prototype.WFa=function(w){this.trigger(la.a.Events.PART_READY,[{Hb:w,error:"Requested part not found",Bk:!1,Dh:!1}])};e.prototype.Xza=function(w,ea,y){this.Q8[w]=!0;this.trigger(la.a.Events.PART_READY,[{Hb:w,data:ea,Bk:!1,Dh:!1,error:null,ie:y}])};return e}(la.a);Object(n.a)(xa);Object(n.b)(xa);ta["default"]=xa}}]);}).call(this || window)
