/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{567:function(xa,ta,n){function qa(){return!1}function na(ea,y,ba){if(!(y in w))return!0;y=w[y];for(var x=0;x<y.length;x++){var fa=ea;var ca=y[x];var ma=ba;if(ca.name in fa){var ka="",ja=!1;fa=fa[ca.name];switch(ca.type){case "s":ka="String";ja=Object(la.isString)(fa);break;case "a":ka="Array";ja=Object(la.isArray)(fa);break;case "n":ka="Number";ja=Object(la.isNumber)(fa)&&Object(la.isFinite)(fa);break;case "o":ka="Object",ja=
Object(la.isObject)(fa)&&!Object(la.isArray)(fa)}ja||ma.reject('Expected response field "'+ca.name+'" to have type '+ka);ca=ja}else ma.reject('Response missing field "'+ca.name+'"'),ca=!1;if(!ca)return!1}return!0}function oa(ea){for(var y=0,ba=["locale","excelMaxAllowedCellCount","applyPageBreaksToSheet","excelDefaultCellBorderWidth","displayChangeTracking"];y<ba.length;y++){var x=ba[y],fa=x;x=x.charAt(0).toUpperCase()+x.slice(1);ea[fa]&&(Object.defineProperty(ea,x,Object.getOwnPropertyDescriptor(ea,
fa)),delete ea[fa])}return ea}n.r(ta);var ha=n(0),la=n(1);n.n(la);var ia=n(3);xa=n(54);var z=n(33),aa=n(585),r=n(116),h=n(477),f=n(50),a=n(205),b=function(){function ea(){this.request=this.result=null;this.state=0;var y=this;y.promise=new Promise(function(ba,x){y.resolve=function(){if(0===y.state||4===y.state)y.state=1,y.result=arguments[0],ba.apply(null,arguments)};y.reject=function(){if(0===y.state||4===y.state)y.state=2,x.apply(null,arguments)}})}ea.prototype.$w=function(){return 1===(this.state&
1)};ea.prototype.Qva=function(){return 2===(this.state&2)};ea.prototype.Wk=function(){return!this.Qva()&&!this.$w()};ea.prototype.kva=function(){return 4===(this.state&4)};ea.prototype.eV=function(){this.state|=4};return ea}(),e=function(){function ea(){this.Kw={};this.Ac=[]}ea.prototype.pop=function(){var y=this.Ac.pop();this.Kw[y.key]=void 0;return y};ea.prototype.push=function(y,ba){ba={key:y,data:ba};this.Ac.push(ba);this.Kw[y]=ba.data};ea.prototype.contains=function(y){return!!this.Kw[y]};ea.prototype.get=
function(y){return this.Kw[y]};ea.prototype.set=function(y,ba){var x=this;this.Kw[y]=ba;this.Ac.forEach(function(fa,ca){fa.key===y&&(x.Ac[ca]=fa)})};ea.prototype.remove=function(y){var ba=this;this.Kw[y]=void 0;this.Ac.forEach(function(x,fa){x.key===y&&ba.Ac.splice(fa,1)})};ea.prototype.length=function(){return this.Ac.length};return ea}(),w={pages:[{name:"pages",type:"a"}],pdf:[{name:"url",type:"s"}],docmod:[{name:"url",type:"s"},{name:"rID",type:"s"}],health:[],tiles:[{name:"z",type:"n"},{name:"rID",
type:"n"},{name:"tiles",type:"a"},{name:"size",type:"n"}],cAnnots:[{name:"annots",type:"a"}],annots:[{name:"url",type:"s"},{name:"name",type:"s"}],image:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],text:[{name:"url",type:"s"},{name:"name",type:"s"},{name:"p",type:"n"}],ApString2Xod:[{name:"url",type:"s"},{name:"rID",type:"s"}]};n=function(){function ea(y,ba,x){var fa=this;this.MV=this.G1=!1;this.Ri=this.RL=this.Fy=this.Kf=this.aA=this.rr=this.$z=this.Gp=null;this.gp=new b;this.Ps=
new b;this.cH=!1;this.Xg=this.Pf=this.Qf=this.Lg=null;this.th=[];this.WH=[];this.cache={};this.timeStamp=0;this.Ki=[];this.hl=[];this.aQ=null;this.q1=!1;this.n$=this.id=null;this.JS=this.M4=qa;this.mh=0;this.zR=!1;this.V6=1;this.bl={};this.Av=0;this.Kx=new e;ba.endsWith("/")||(ba+="/");x=x||{};this.G1=x.disableWebsockets||!1;this.MV=x.singleServerMode||!1;null!=x.customQueryParameters&&Object(f.b)("wvsQueryParameters",x.customQueryParameters);ba.endsWith("blackbox/")||(ba+="blackbox/");this.Gp=x.uploadData||
null;this.Fy=x.uriData||null;this.$z=x.cacheKey||null;if(this.rr=x.officeOptions||null)this.rr=oa(this.rr);this.Kf=x.rasterizerOptions||null;this.aA=x.cadOptions||null;this.jg=ba;this.BP=y;this.Dr(!0);this.Rv=(new aa.a(ba,null,this.zj())).nqa(!this.G1,function(ca){fa.Jxa(ca)},function(){return null},function(){fa.cH=!1},function(){fa.wBa()})}ea.prototype.tma=function(){var y=this;return new Promise(function(ba,x){var fa=new XMLHttpRequest;fa.open("GET",y.jg+"ck");fa.withCredentials=y.zj();fa.onreadystatechange=
function(){fa.readyState===XMLHttpRequest.DONE&&(200===fa.status?ba():x())};fa.send()})};ea.prototype.pDa=function(y){this.M4=y||qa;this.JS=qa};ea.prototype.yka=function(){this.G9();return this.Rv.dt()};ea.prototype.G9=function(){Object(ha.b)(this,void 0,void 0,function(){return Object(ha.d)(this,function(y){switch(y.label){case 0:return this.Ps=new b,this.gp=new b,this.cH=!1,this.id=null,this.q1=!1,[4,this.tma().catch(function(){})];case 1:return y.ba(),[2]}})})};ea.prototype.wBa=function(){this.M4();
this.G9();this.Lg&&(this.Lg.Wk()?this.Wi(this.Lg.request):this.Lg.$w()&&this.JS(this.Lg.result.url,"pdf")&&(this.Lg=null,this.D9()));this.Xg&&this.Xg.Wk()&&this.Wi(this.Xg.request);this.Qf&&this.Qf.Wk()?this.Wi(this.Qf.request):this.Pf&&this.Pf.Wk()&&this.u4();var y;for(y=0;y<this.Ki.length;y++)this.Ki[y]&&(this.Ki[y].Wk()?this.Wi(this.Ki[y].request):this.Ki[y].$w()&&this.JS(this.Ki[y].result.url,"image")&&(this.Ki[y]=null,this.JK(Object(la.uniqueId)(),y)));for(y=0;y<this.hl.length;y++)this.hl[y]&&
this.hl[y].Wk()&&!this.hl[y].kva()&&this.Wi(this.hl[y].request);for(y=0;y<this.th.length;y++)this.th[y]&&this.th[y].Wk()&&this.Wi(this.th[y].request)};ea.prototype.Dua=function(){return this.cH?Promise.resolve():(this.cH=!0,this.timeStamp=Date.now(),this.Rv.gJ())};ea.prototype.DGa=function(){var y=this,ba,x,fa,ca,ma;return new Promise(function(ka,ja){if(y.Gp)ba=new FormData,ba.append("file",y.Gp.fileHandle,y.Gp.fileHandle.name),y.rr&&ba.append("officeOptions",JSON.stringify(y.rr)),y.Kf&&ba.append("rasterizerOptions",
JSON.stringify(y.Kf)),y.aA&&ba.append("cadOptions",y.aA.getJsonString()),y.$z&&ba.append("cacheKey",y.$z),x=y.Gp.loadCallback,ca="upload",fa=y.Gp.extension;else if(y.Fy)ba={uri:y.Fy.uri,uLa:y.Fy.shareId},ba=Object.keys(ba).map(function(sa){return sa+"="+(ba[sa]?encodeURIComponent(ba[sa]):"")}).join("&"),ma="application/x-www-form-urlencoded; charset=UTF-8",x=y.Fy.loadCallback,ca="url",fa=y.Fy.extension;else{ka();return}var ra=new XMLHttpRequest,pa=Object(z.k)(y.jg,"AuxUpload");pa=Object(a.a)(pa,{type:ca,
ext:fa});ra.open("POST",pa);ra.withCredentials=y.zj();ma&&ra.setRequestHeader("Content-Type",ma);ra.addEventListener("load",function(){if(ra.readyState===ra.DONE&&200===ra.status){var sa=JSON.parse(ra.response);y.BP=sa.uri;x(sa);ka(sa)}});ra.addEventListener("error",function(){ja(ra.statusText+" "+JSON.stringify(ra))});y.Gp&&null!=y.Gp.onProgress&&(ra.upload.onprogress=function(sa){y.Gp.onProgress(sa)});ra.send(ba)})};ea.prototype.lBa=function(y){this.password=y||null;this.gp.$w()||(this.gp=new b,
this.Wi({t:"pages"}));return this.gp.promise};ea.prototype.mD=function(y){this.aQ=y||null;this.gp.$w()||this.Wi({t:"pages"});return this.gp.promise};ea.prototype.lA=function(y){y=Object.assign(y,{uri:encodeURIComponent(this.BP)});this.aQ&&(y.ext=this.aQ);this.Ri&&(y.c=this.Ri);this.password&&(y.pswd=this.password);this.$z&&(y.cacheKey=this.$z);this.rr&&(y.officeOptions=this.rr);this.Kf&&(y.rastOptions=this.Kf);this.aA&&(y.cadOptions=this.aA.mImpl);return y};ea.prototype.bCa=function(){0<this.Kx.length()&&
10>=this.Av&&this.cCa(this.Kx.pop().data)};ea.prototype.Kja=function(y){0<this.Kx.length()&&this.Kx.contains(y)&&this.Kx.remove(y)};ea.prototype.Wi=function(y){y=this.lA(y);this.Rv.send(y)};ea.prototype.i$=function(y,ba){10<this.Av?this.Kx.push(y,ba):(this.Av++,y=this.lA(ba),this.Rv.send(y))};ea.prototype.cCa=function(y){this.Av++;y=this.lA(y);this.Rv.send(y)};ea.prototype.fo=function(y){return y};ea.prototype.L4=function(y){this.MV&&y?Object(ia.j)("Server failed health check. Single server mode ignoring check."):
!this.HJa&&y&&3>=this.mh?(this.zR=!0,this.Rv.dt()):3<this.mh&&(this.MV=!0)};ea.prototype.Jxa=function(y){var ba=this,x=y.data,fa=y.err,ca=y.t;switch(ca){case "upload":fa?this.EGa.reject(fa):this.EGa.resolve("Success");break;case "pages":fa?this.gp.reject(fa):na(x,ca,this.gp)&&this.gp.resolve(x);break;case "config":if(fa)this.Ps.reject(fa);else if(na(x,ca,this.Ps)){this.L4(x.unhealthy);x.id&&(this.id=x.id);if(x.auth){var ma=Object(f.a)("wvsQueryParameters");ma.auth=x.auth;Object(f.b)("wvsQueryParameters",
ma)}x.serverVersion&&(this.RL=x.serverVersion,Object(ia.h)("[WebViewer Server] server version: "+this.RL));x.serverID?(this.mh=x.serverID===this.n$&&this.zR?this.mh+1:0,this.n$=x.serverID):this.mh=0;this.zR=!1;this.Ps.resolve(x)}break;case "health":fa?this.Ps.reject(fa):na(x,ca,this.Ps)&&this.L4(x.unhealthy);break;case "pdf":x.url=Object(a.a)(this.jg+"../"+encodeURI(x.url));fa?this.Lg.reject(fa):na(x,ca,this.Lg)&&this.Lg.resolve(x);break;case "ApString2Xod":x.url=Object(a.a)(this.jg+"../data/"+encodeURI(x.url));
fa?this.bl[x.rID].reject(fa):na(x,ca,this.bl[x.rID])&&this.bl[x.rID].resolve(x);break;case "docmod":x.url=Object(a.a)(this.jg+"../"+encodeURI(x.url));fa?this.bl[x.rID].reject(fa):na(x,ca,this.Lg)&&this.bl[x.rID].resolve(x);break;case "xod":if(fa)this.Qf&&this.Qf.Wk()&&this.Qf.reject(fa),this.Pf&&this.Pf.Wk()&&this.Pf.reject(fa);else if(x.notFound)x.noCreate||this.Qf&&this.Qf.Wk()&&this.Qf.resolve(x),this.Pf&&this.Pf.Wk()&&this.Pf.resolve(x);else{x.url&&(x.url=Object(a.a)(this.jg+"../"+encodeURI(x.url)));
if(!this.Pf||this.Pf.$w())this.Pf=new b,this.Pf.request={t:"xod",noCreate:!0};this.Qf||(this.Qf=new b,this.Qf.request={t:"xod"});this.Pf.resolve(x);this.Qf.resolve(x)}break;case "cAnnots":ma=this.Xg;if(fa)ma.reject(fa);else if(na(x,ca,ma)){ma.eV();var ka=[],ja=x.annots;x=function(Fa){var Da=ja[Fa].s,Ba=ja[Fa].e,Ma=ra.jg+"../"+encodeURI(ja[Fa].xfdf),Ha="true"===ja[Fa].hasAppearance?Object(a.a)(Ma+".xodapp"):null,Ia=Object(la.range)(Da,Ba+1);ka[Fa]={range:Ia,promise:new Promise(function(Na,Pa){var Qa=
new XMLHttpRequest;Qa.open("GET",Object(a.a)(Ma));Qa.responseType="text";Qa.withCredentials=ba.zj();Qa.addEventListener("load",function(){Qa.readyState===Qa.DONE&&200===Qa.status&&Na({Mu:Qa.response,Sn:Ha,range:Ia})});Qa.addEventListener("error",function(){Pa(Qa.statusText+" "+JSON.stringify(Qa))});Qa.send()})}};var ra=this;for(fa=0;fa<ja.length;fa++)x(fa);ma.resolve(ka)}break;case "annots":if(fa)this.Xg.reject(fa);else if(na(x,ca,this.Xg)){this.Xg.eV();var pa=new XMLHttpRequest;ma=this.jg+"../"+
encodeURI(x.url);var sa=x.hasAppearance?Object(a.a)(ma+".xodapp"):null;pa.open("GET",Object(a.a)(ma));pa.responseType="text";pa.withCredentials=this.zj();pa.addEventListener("load",function(){pa.readyState===pa.DONE&&200===pa.status&&ba.Xg.resolve({Mu:pa.response,Sn:sa})});pa.addEventListener("error",function(){ba.Xg.reject(pa.statusText+" "+JSON.stringify(pa))});pa.send()}break;case "image":this.Av--;var ua=this.Ki[x.p];fa?ua.promise.reject(fa):na(x,ca,ua)&&(ua.result=x,ua.result.url=Object(a.a)(this.jg+
"../"+encodeURI(ua.result.url)),ua.resolve(ua.result));break;case "tiles":this.Av--;ua=x.rID;ma=this.th[ua];this.th[ua]=null;this.WH.push(ua);if(fa)ma.reject(fa);else if(na(x,ca,ma)){for(fa=0;fa<x.tiles.length;fa++)x.tiles[fa]=Object(a.a)(this.jg+"../"+encodeURI(x.tiles[fa]));ma.resolve(x)}break;case "text":ua=this.hl[x.p];if(fa)ua.reject(fa);else if(na(x,ca,ua)){ua.eV();var wa=new XMLHttpRequest;x=Object(a.a)(this.jg+"../"+encodeURI(x.url));wa.open("GET",x);wa.withCredentials=this.zj();wa.addEventListener("load",
function(){wa.readyState===wa.DONE&&200===wa.status&&(ua.result=JSON.parse(wa.response),ua.resolve(ua.result))});wa.addEventListener("error",function(Fa){ua.reject(wa.statusText+" "+JSON.stringify(Fa))});wa.send()}break;case "progress":"loading"===x.t&&this.trigger(r.a.Events.DOCUMENT_LOADING_PROGRESS,[x.bytes,x.total])}this.bCa();!ca&&y.echo&&y&&"apstring2xod"===y.echo.t&&(y=y.echo.reqID)&&(2<=parseInt(this.RL,10)?this.bl[y].reject("Message unhandled by server"):this.bl[y].reject())};ea.prototype.Wqa=
function(){return Object(ha.b)(this,void 0,void 0,function(){return Object(ha.d)(this,function(y){switch(y.label){case 0:return[4,this.Dua()];case 1:return y.ba(),[2,this.Ps.promise]}})})};ea.prototype.Aqa=function(y){for(var ba=this,x=new XMLHttpRequest,fa=Object(a.a)(this.jg+"aul",{id:this.id}),ca=new FormData,ma={},ka=0;ka<y.body.length;ka++){var ja=y.body[ka];ma[ja.id]=ja.jO.w+";"+ja.jO.h;ca.append(ja.id,ja.jO.dataString)}y={t:"apstring2xod",reqID:this.V6++,parts:ma};var ra=this.lA(y);ca.append("msg",
JSON.stringify(ra));this.bl[ra.reqID]=new b;x.open("POST",fa);x.withCredentials=this.zj;fa=new Promise(function(pa,sa){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?pa():sa("An error occurred while sending down appearance strings to the server"))}});x.send(ca);return fa.then(function(){return ba.bl[ra.reqID].promise})};ea.prototype.Cka=function(){var y=this.RL.split("-")[0].split("."),ba=["1","5","9"];if(3!==y.length)throw Error("Invalid WVS version length.");if(3!==ba.length)throw Error("Invalid version length.");
for(var x=0;x<y.length;++x){if(ba.length===x||y[x]>ba[x])return-1;if(y[x]!==ba[x])return 1}return 0};ea.prototype.Js=function(){return 0>=this.Cka()};ea.prototype.kQ=function(){this.Xg||(this.Xg=new b,this.Js()?this.Xg.request={t:"cAnnots"}:this.Xg.request={t:"annots"},this.Wi(this.Xg.request));return this.Xg.promise};ea.prototype.JK=function(y,ba){this.Ki[ba]||(this.Ki[ba]=new b,this.Ki[ba].request={t:"image",p:ba},this.i$(y,this.Ki[ba].request));return this.Ki[ba].promise};ea.prototype.mBa=function(y){this.hl[y]||
(this.hl[y]=new b,this.hl[y].request={t:"text",p:y},this.Wi(this.hl[y].request));return this.hl[y].promise};ea.prototype.nBa=function(y,ba,x,fa,ca){var ma=this.th.length;this.WH.length&&(ma=this.WH.pop());this.th[ma]=new b;this.th[ma].request={t:"tiles",p:ba,z:x,r:fa,size:ca,rID:ma};this.i$(y,this.th[ma].request);return this.th[ma].promise};ea.prototype.D9=function(){this.Lg||(this.Lg=new b,this.Lg.request={t:"pdf"},this.q1?this.Lg.resolve({url:this.BP}):this.Wi(this.Lg.request));return this.Lg.promise};
ea.prototype.C3=function(y){var ba=this,x=new XMLHttpRequest,fa=Object(a.a)(this.jg+"aul",{id:this.id}),ca=new FormData,ma={};y.annots&&(ma.annots="xfdf");y.watermark&&(ma.watermark="png");y.redactions&&(ma.redactions="redact");ma={t:"docmod",reqID:this.V6++,parts:ma};y.print&&(ma.print=!0);var ka=this.lA(ma);ca.append("msg",JSON.stringify(ka));return Promise.all([y.annots,y.watermark,y.redactions].map(function(ja){return Promise.resolve(ja)})).then(function(ja){var ra=ja[0],pa=ja[1];ja=ja[2];ra&&
ca.append("annots",ra);pa&&ca.append("watermark",pa);ja&&ca.append("redactions",ja);ba.bl[ka.reqID]=new b;x.open("POST",fa);x.withCredentials=ba.zj;ra=new Promise(function(sa,ua){x.onreadystatechange=function(){4===x.readyState&&(200===x.status?sa():ua("An error occurred while sending down annotation data to the server"))}});x.send(ca);return ra.then(function(){return ba.bl[ka.reqID].promise})})};ea.prototype.u4=function(){this.Pf||(this.Pf=new b,this.Pf.request={t:"xod",noCreate:!0},this.Wi(this.Pf.request));
return this.Pf.promise};ea.prototype.oBa=function(){this.Qf||(this.Qf=new b,this.Qf.request={t:"xod"},this.Wi(this.Qf.request));return this.Qf.promise};ea.prototype.zr=function(){return!0};ea.prototype.request=function(){};ea.prototype.P8=function(){};ea.prototype.abort=function(){for(var y=0;y<this.th.length;y++)this.th[y]&&(this.th[y].resolve(null),this.th[y]=null,this.WH.push(y));this.close()};ea.prototype.XK=function(y){this.Ri=this.Ri||{};this.Ri.headers=y};ea.prototype.Dr=function(y){this.Ri=
this.Ri||{};this.Ri.internal=this.Ri.internal||{};this.Ri.internal.withCredentials=y};ea.prototype.zj=function(){return this.Ri&&this.Ri.internal?this.Ri.internal.withCredentials:null};ea.prototype.getFileData=function(){return Promise.reject()};return ea}();Object(xa.a)(n);Object(h.a)(n);Object(h.b)(n);ta["default"]=n},585:function(xa,ta,n){var qa=n(0),na=n(3),oa=n(33),ha=n(50),la=n(205),ia=n(93),z=function(){function r(h,f,a,b,e,w){void 0===a&&(a=null);void 0===b&&(b=null);void 0===e&&(e=null);
void 0===w&&(w=null);this.mh=0;this.VS=!1;this.mC=8;this.R9=3E3;this.d0=this.$Ga(h);this.url=f?this.d0+"/"+f:this.d0+"/ws";this.lP=a;this.FC=b;this.jA=e;this.E9=w}r.prototype.$Ga=function(h){var f=h.indexOf("://"),a="ws://";0>f?f=0:(5===f&&(a="wss://"),f+=3);var b=h.lastIndexOf("/");0>b&&(b=h.length);return a+h.slice(f,b)};r.prototype.send=function(h){this.Or.readyState===WebSocket.CLOSED||this.VS||this.Or.send(JSON.stringify(h))};r.prototype.gJ=function(){return Object(qa.b)(this,void 0,void 0,function(){var h,
f=this;return Object(qa.d)(this,function(){h=Object(ha.a)("wvsQueryParameters");h.bcid=Object(oa.l)(8);Object(ha.b)("wvsQueryParameters",h);return[2,new Promise(function(a,b){var e=Object(la.a)(f.url);f.Or=new WebSocket(e);f.Or.onopen=function(){f.VS=!1;f.mh=0;f.FC&&f.FC();a()};f.Or.onerror=function(){f.VS=!0};f.Or.onclose=function(w){w=w.code;f.jA&&f.jA();1E3!==w&&3E3!==w&&f.$ta(a,b)};f.Or.onmessage=function(w){w&&w.data&&(w=JSON.parse(w.data),w.hb?f.send({hb:!0}):w.end?close():f.lP(w))}})]})})};
r.prototype.$ta=function(h,f){Object(qa.b)(this,void 0,void 0,function(){var a=this;return Object(qa.d)(this,function(){this.mh<this.mC?setTimeout(function(){a.mh++;Object(na.j)("Reconnecting to WebViewer Server, attempt "+a.mh+" of "+a.mC+" ...");a.gJ().then(h).catch(f)},this.R9):f(ia.a);return[2]})})};r.prototype.dt=function(){var h;void 0===h&&(h=!1);this.mh=0;h?this.Or.close(3E3):this.Or.close();return Promise.resolve()};return r}(),aa=function(){function r(h,f,a,b,e,w,ea){void 0===b&&(b=null);
void 0===e&&(e=null);void 0===w&&(w=null);void 0===ea&&(ea=null);this.mh=this.IK=this.id=0;this.GB=!1;this.request=null;this.mC=8;this.R9=3E3;h=this.tza(h);this.url=f?h+"/"+f+"pf":h+"/pf";this.JL=a;this.lP=b;this.FC=e;this.jA=w;this.E9=ea}r.prototype.tza=function(h){var f=h.lastIndexOf("/");0>f&&(f=h.length);return h.slice(0,f)};r.prototype.Vla=function(h){h=h.split("\n");for(h[h.length-1]&&h.pop();0<h.length&&3>h[h.length-1].length;)"]"===h.pop()&&(this.id=0);0<h.length&&3>h[0].length&&h.shift();
for(var f=0;f<h.length;++f)h[f].endsWith(",")&&(h[f]=h[f].substr(0,h[f].length-1));return h};r.prototype.Q9=function(){return Object(qa.b)(this,void 0,void 0,function(){var h=this;return Object(qa.d)(this,function(f){switch(f.label){case 0:return this.mh++<this.mC?[4,new Promise(function(a){return setTimeout(function(){h.E9();h.gJ();a()},3E3)})]:[3,2];case 1:f.ba(),f.label=2;case 2:return[2]}})})};r.prototype.vza=function(h){Object(qa.b)(this,void 0,void 0,function(){var f,a;return Object(qa.d)(this,
function(b){switch(b.label){case 0:f=null,a=0,b.label=1;case 1:if(!(a<h.length))return[3,6];f=JSON.parse(h[a]);if(!f)return[3,5];if(!f.end)return[3,2];close();return[3,5];case 2:if(!f.id||Number(f.id)===this.id)return[3,4];Object(na.j)("Reconnecting, new server detected");this.dt();return[4,this.Q9()];case 3:return b.ba(),[3,5];case 4:f.hb&&Number(f.id)===this.id?this.send({hb:!0}):this.GB||this.lP(f),b.label=5;case 5:return++a,[3,1];case 6:return[2]}})})};r.prototype.Exa=function(h){Object(qa.b)(this,
void 0,void 0,function(){var f,a,b;return Object(qa.d)(this,function(e){switch(e.label){case 0:if(!(3<=h.readyState))return[3,2];try{f=h.responseText.length}catch(w){return Object(na.h)("caught exception"),[2]}if(0<f)try{a=this.Vla(h.responseText),0===this.id&&0<a.length&&(b=JSON.parse(a.shift()),this.id=b.id,this.mh=0),this.vza(a)}catch(w){}return this.GB?[3,2]:[4,this.s2()];case 1:e.ba(),e.label=2;case 2:return[2]}})})};r.prototype.s2=function(){return Object(qa.b)(this,void 0,void 0,function(){var h=
this;return Object(qa.d)(this,function(){return[2,new Promise(function(f,a){function b(){return Object(qa.b)(h,void 0,void 0,function(){return Object(qa.d)(this,function(w){switch(w.label){case 0:a(),this.dt(),w.label=1;case 1:return this.GB&&this.mh<this.mC?[4,this.Q9()]:[3,3];case 2:return w.ba(),[3,1];case 3:return[2]}})})}h.request=new XMLHttpRequest;h.request.withCredentials=h.JL;var e=Object(la.a)(h.url,0!==h.id?{id:String(h.id),uc:String(h.IK)}:{uc:String(h.IK)});h.IK++;h.request.open("GET",
e,!0);h.request.setRequestHeader("Cache-Control","no-cache");h.request.setRequestHeader("X-Requested-With","XMLHttpRequest");h.request.onreadystatechange=function(){h.Exa(h.request)};h.request.addEventListener("error",b);h.request.addEventListener("timeout",b);h.request.addEventListener("load",function(){h.FC&&h.FC();f()});h.request.send()})]})})};r.prototype.gJ=function(){var h=Object(ha.a)("wvsQueryParameters");h.bcid=Object(oa.l)(8);Object(ha.b)("wvsQueryParameters",h);this.IK=this.id=0;this.GB=
!1;return this.s2()};r.prototype.send=function(h){var f=this,a=new XMLHttpRequest;a.withCredentials=this.JL;var b=Object(la.a)(this.url,{id:String(this.id)}),e=new FormData;e.append("data",JSON.stringify(h));a.addEventListener("error",function(){f.dt()});a.open("POST",b);a.setRequestHeader("X-Requested-With","XMLHttpRequest");a.send(e)};r.prototype.dt=function(){this.id=0;this.GB=!0;this.jA&&this.jA();this.request.abort();return Promise.resolve()};return r}();xa=function(){function r(h,f,a){this.M0=
h;this.target=f;this.JL=a}r.prototype.nqa=function(h,f,a,b,e){void 0===h&&(h=!0);void 0===f&&(f=null);void 0===a&&(a=null);void 0===b&&(b=null);void 0===e&&(e=null);return h?new z(this.M0,this.target,f,a,b,e):new aa(this.M0,this.target,this.JL,f,a,b,e)};return r}();ta.a=xa}}]);}).call(this || window)
